import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import MouseGlow from '@/components/ui/MouseGlow';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // sesuaikan kebutuhanmu
  variable: '--font-poppins',    // akan jadi CSS variable
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Khoirul Aziz ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {/* <MouseGlow/> */}
        {children}
      </body>
    </html>
  );
}
